# Compiler and options for Intel
FC = $(MPIHOME)/bin/mpif90

# ^_^ tell the code we're using ifort
CPPFLAGS=-DIFORT

FFLAGSOPT = -O3  
FFLAGSDEBUG =-g  -check all -warn all

LDFLAGS = -Wl,-rpath=$(SEHOME)/lib 
