# Compiler and options for gfortran/Darwin/i386
FC = $(MPIHOME)/bin/mpif90

# ^_^ tell the code we're using gfort
CPPFLAGS=-DGFORT

FFLAGSOPT= -ffixed-line-length-132 -O3
FFLAGSDEBUG=-ffixed-line-length-132  -Wall

